Repository dodorare/crossbow, pull requests merged in 2022-07, with the labels that each got.

#99 Optimize crossbow processes
  crossbundle/cli/Cargo.toml
  crossbundle/cli/src/commands/build/android.rs
  crossbundle/cli/src/lib.rs
  crossbundle/cli/tests/build_gradle.rs
  crossbundle/cli/tests/execute_aab.rs
  crossbundle/cli/tests/execute_apk.rs
  crossbundle/tools/src/commands/android/add_libs_into_apk.rs
  crossbundle/tools/src/commands/android/gradle_command.rs
  crossbundle/tools/src/commands/common/gen_minimal_project/consts.rs
  crossbundle/tools/tests/aab_full.rs
  crossbundle/tools/tests/android_full.rs
  crossbundle/tools/tests/gen_gradle_project.rs
  docs/crossbow-plugins.md
Labels: enhancement

#100 Replace Metadata with AndroidConfig and AppleConfig
  crossbundle/cli/src/commands/build/android.rs
  crossbundle/cli/src/commands/build/build_context.rs
  crossbundle/cli/src/error.rs
  crossbundle/cli/src/lib.rs
  crossbundle/cli/src/types/android_config.rs
  crossbundle/cli/src/types/apple_config.rs
  crossbundle/cli/src/types/mod.rs
  crossbundle/cli/tests/execute_apk.rs
  crossbundle/tools/src/commands/android/generate/gen_manifest.rs
  crossbundle/tools/src/commands/android/generate/gen_minimal_unsigned_aab.rs
  crossbundle/tools/src/commands/android/generate/mod.rs
  crossbundle/tools/src/commands/android/mod.rs
  crossbundle/tools/src/commands/common/gen_minimal_project/consts.rs
  crossbundle/tools/tests/aapt2.rs
Labels: enhancement

#104 Add documentation and refactor
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs_improvement.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .github/scripts/publish_crates.sh
  .github/workflows/publish.yml
  Cargo.toml
  README.md
  crossbundle/cli/Cargo.toml
  crossbundle/cli/README.md
  crossbundle/tools/Cargo.toml
  docs/crossbow-permissions.md
  docs/crossbow-plugin.md
  docs/crossbow-plugins.md
  docs/crossbundle-gradle.md
  examples/bevy-2d/Cargo.toml
  examples/bevy-3d/Cargo.toml
  examples/bevy-explorer/Cargo.toml
  examples/macroquad-3d/Cargo.toml
  examples/macroquad-3d/src/main.rs
  examples/macroquad-permissions/Cargo.toml
  examples/macroquad-permissions/src/main.rs
  platform/android/Cargo.toml
  platform/android/README.md
  platform/android/java/app/config.gradle
  platform/android/src/permission.rs
  plugins/admob-android/README.md
  plugins/admob/Cargo.toml
  plugins/admob/README.md
  plugins/admob/android/AndroidManifest.xml
  plugins/admob/android/build.gradle
  plugins/admob/android/config.gradle
  plugins/admob/android/gradle.properties
  plugins/admob/android/publish.gradle
  plugins/admob/android/settings.gradle
  plugins/admob/android/src/com/crossbow/admob/AdMob.kt
  plugins/admob/src/lib.rs
  src/lib.rs
  src/permission.rs
Labels: documentation, enhancement

#109 Fix android build on Windows, start_apk function and Kotlin linking
  .github/workflows/ci.yml
  Cargo.toml
  crossbundle/cli/Cargo.toml
  crossbundle/cli/src/commands/build/android.rs
  crossbundle/cli/src/commands/run/android.rs
  crossbundle/cli/src/types/mod.rs
  crossbundle/cli/tests/cargo_metadata.rs
  crossbundle/tools/Cargo.toml
  crossbundle/tools/src/commands/android/generate/gen_gradle_project.rs
  crossbundle/tools/src/commands/android/start_apk.rs
  crossbundle/tools/src/commands/common/gen_minimal_project/consts.rs
  crossbundle/tools/src/commands/common/gen_minimal_project/gen_min_project.rs
  deny.toml
  examples/bevy-2d/Cargo.toml
  examples/bevy-3d/Cargo.toml
  examples/bevy-explorer/Cargo.toml
  examples/macroquad-3d/Cargo.toml
  examples/macroquad-permissions/Cargo.toml
  platform/android/Cargo.toml
  platform/android/java/app/build.gradle
  platform/android/java/app/config.gradle
  platform/android/java/lib/src/com/crossbow/library/CrossbowLib.kt
  platform/android/java/lib/src/com/crossbow/library/plugin/CrossbowPlugin.kt
  platform/android/java/lib/src/com/crossbow/library/plugin/SignalInfo.kt
  platform/android/src/externs/mod.rs
  plugins/admob/Cargo.toml
  plugins/admob/README.md
  plugins/admob/android/config.gradle
Labels: bug, high priority

#110 Fix docs
  docs/crossbundle-install-command.md
Labels: documentation, high priority

#111 Add basic iOS Platform Implementation
  .github/pull_request_template.md
  .github/scripts/publish_crates.sh
  .github/workflows/publish.yml
  Cargo.toml
  README.md
  crossbundle/cli/src/commands/build/apple.rs
  crossbundle/cli/src/commands/build/build_context.rs
  crossbundle/cli/src/error.rs
  crossbundle/cli/src/types/android_config.rs
  crossbundle/cli/src/types/apple_config.rs
  crossbundle/tools/src/commands/apple/save_plist.rs
  crossbundle/tools/src/error.rs
  crossbundle/tools/tests/apple_full.rs
  examples/macroquad-permissions/Cargo.toml
  examples/macroquad-permissions/src/main.rs
  platform/android/src/error.rs
  platform/ios/Cargo.toml
  platform/ios/README.md
  platform/ios/build.rs
  platform/ios/src/error.rs
  platform/ios/src/lib.rs
  platform/ios/src/permission.rs
  platform/ios/src/types/mod.rs
  platform/ios/src/types/permission.rs
  src/error.rs
  src/lib.rs
  src/permission.rs
Labels: enhancement, high priority

#115 Fix issue with install several packages
  .github/workflows/ci.yml
  crossbundle/cli/Cargo.toml
  crossbundle/cli/src/commands/build/android.rs
  crossbundle/cli/src/commands/install/command_line_tools.rs
  crossbundle/cli/src/commands/install/sdkmanager.rs
  crossbundle/tools/Cargo.toml
  crossbundle/tools/src/commands/android/generate/gen_key.rs
  crossbundle/tools/src/commands/android/sign_apk.rs
  crossbundle/tools/src/tools/android_ndk.rs
  crossbundle/tools/src/tools/android_sdk.rs
  crossbundle/tools/tests/bundletool.rs
  docs/crossbundle-install-command.md
Labels: bug, documentation

#118 Add generic permissions
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/ci.yml
  README.md
  crossbundle/cli/Cargo.toml
  crossbundle/cli/src/commands/build/android.rs
  crossbundle/cli/src/commands/install/command_line_tools.rs
  crossbundle/cli/src/commands/install/sdkmanager.rs
  crossbundle/tools/Cargo.toml
  crossbundle/tools/src/commands/android/generate/gen_key.rs
  crossbundle/tools/src/commands/android/sign_apk.rs
  crossbundle/tools/src/tools/android_ndk.rs
  crossbundle/tools/src/tools/android_sdk.rs
  crossbundle/tools/tests/bundletool.rs
  docs/crossbundle-install-command.md
  examples/macroquad-permissions/Cargo.toml
  examples/macroquad-permissions/src/main.rs
  platform/android/java/lib/src/com/crossbow/library/Crossbow.kt
  platform/android/java/lib/src/com/crossbow/library/CrossbowLib.kt
  platform/android/java/lib/src/com/crossbow/library/PermissionsUtil.kt
  platform/android/src/externs/crossbow_lib.rs
  platform/android/src/externs/crossbow_plugin.rs
  platform/android/src/lib.rs
  platform/android/src/permission/android_permission.rs
  platform/android/src/permission/handlers.rs
  platform/android/src/permission/mod.rs
  platform/android/src/permission/request_permission.rs
  platform/android/src/plugin/handlers.rs
  platform/android/src/plugin/jni_rust_type.rs
  platform/android/src/plugin/jni_singleton.rs
  platform/android/src/plugin/mod.rs
  platform/android/src/types/android_permission_group.rs
  platform/android/src/types/mod.rs
  platform/ios/Cargo.toml
  platform/ios/build.rs
  platform/ios/src/lib.rs
  platform/ios/src/permission.rs
  platform/ios/src/permission/mod.rs
  platform/ios/src/permission/request_permission.rs
  platform/ios/src/permission/types.rs
  platform/ios/src/types/mod.rs
  platform/ios/src/types/permission.rs
  plugins/admob/README.md
  plugins/admob/src/lib.rs
  src/permission.rs
  src/permission/mod.rs
  src/permission/request_permission.rs
  src/permission/status.rs
Labels: enhancement, high priority

#124 Update Docker image and add CI test of it
  .github/docker/crossbundle.Dockerfile
  .github/workflows/ci.yml
  Cargo.toml
  crossbundle/cli/Cargo.toml
  crossbundle/cli/src/commands/build/android.rs
  crossbundle/cli/src/commands/install/command_line_tools.rs
  crossbundle/cli/src/commands/install/sdkmanager.rs
  crossbundle/tools/Cargo.toml
  crossbundle/tools/src/tools/android_ndk.rs
  crossbundle/tools/src/tools/android_sdk.rs
  docs/src/install/android-linux.md
  docs/src/install/android-macos.md
  docs/src/install/android-windows.md
  docs/src/introduction.md
  examples/bevy-2d/Cargo.toml
  examples/bevy-3d/Cargo.toml
  examples/bevy-explorer/Cargo.toml
  examples/macroquad-3d/Cargo.toml
  examples/macroquad-permissions/Cargo.toml
  platform/android/Cargo.toml
  platform/android/java/app/config.gradle
  platform/ios/Cargo.toml
  plugins/admob/Cargo.toml
  plugins/admob/README.md
  plugins/admob/android/config.gradle
Labels: bug, high priority

#126 Bump version of cmd line tools and bundletool
  crossbundle/cli/Cargo.toml
  crossbundle/cli/src/commands/install/bundletool.rs
  crossbundle/cli/src/commands/install/command_line_tools.rs
Labels: enhancement
